{
 "title": "Mimir / Rollout progress",
 "tags": [ "mimir" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(cortex_build_info, k8s_cluster_unique_name)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(cortex_build_info{k8s_cluster_unique_name=~\"$cluster\"}, service_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rollout progress",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n  sum by (workload) (\n    label_replace(label_replace(label_replace(\n      kube_deployment_status_replicas_updated{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n      or\n      kube_statefulset_status_replicas_updated{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n    , \"workload\", \"$1\", \"deployment\", \"(.+)\"), \"workload\", \"$1\", \"statefulset\", \"(.+)\"), \"workload\", \"$1\", \"workload\", \"(.*?)(?:-zone-[a-z])?\")\n  )\n  /\n  sum by (workload) (\n    label_replace(label_replace(label_replace(\n      kube_deployment_status_replicas{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n      or\n      kube_statefulset_status_replicas{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n    , \"workload\", \"$1\", \"deployment\", \"(.+)\"), \"workload\", \"$1\", \"statefulset\", \"(.+)\"), \"workload\", \"$1\", \"workload\", \"(.*?)(?:-zone-[a-z])?\")\n  )\n) and (\n  sum by (workload) (\n    label_replace(label_replace(label_replace(\n      kube_deployment_status_replicas{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n      or\n      kube_statefulset_status_replicas{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n    , \"workload\", \"$1\", \"deployment\", \"(.+)\"), \"workload\", \"$1\", \"statefulset\", \"(.+)\"), \"workload\", \"$1\", \"workload\", \"(.*?)(?:-zone-[a-z])?\")\n  )\n  > 0\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  sum by (workload) (\n    label_replace(label_replace(label_replace(\n      kube_deployment_status_replicas_ready{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n      or\n      kube_statefulset_status_replicas_ready{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n    , \"workload\", \"$1\", \"deployment\", \"(.+)\"), \"workload\", \"$1\", \"statefulset\", \"(.+)\"), \"workload\", \"$1\", \"workload\", \"(.*?)(?:-zone-[a-z])?\")\n  )\n  /\n  sum by (workload) (\n    label_replace(label_replace(label_replace(\n      kube_deployment_status_replicas{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n      or\n      kube_statefulset_status_replicas{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n    , \"workload\", \"$1\", \"deployment\", \"(.+)\"), \"workload\", \"$1\", \"statefulset\", \"(.+)\"), \"workload\", \"$1\", \"workload\", \"(.*?)(?:-zone-[a-z])?\")\n  )\n) and (\n  sum by (workload) (\n    label_replace(label_replace(label_replace(\n      kube_deployment_status_replicas{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n      or\n      kube_statefulset_status_replicas{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n    , \"workload\", \"$1\", \"deployment\", \"(.+)\"), \"workload\", \"$1\", \"statefulset\", \"(.+)\"), \"workload\", \"$1\", \"workload\", \"(.*?)(?:-zone-[a-z])?\")\n  )\n  > 0\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes - 2xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-distributor.*))\", route=~\"api_(v1|prom)_push|otlp_v1_metrics\",status_code=~\"2.+\"}[$__rate_interval])) /\nsum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-distributor.*))\", route=~\"api_(v1|prom)_push|otlp_v1_metrics\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Writes - 4xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-distributor.*))\", route=~\"api_(v1|prom)_push|otlp_v1_metrics\",status_code=~\"4.+\"}[$__rate_interval])) /\nsum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-distributor.*))\", route=~\"api_(v1|prom)_push|otlp_v1_metrics\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Writes - 5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-distributor.*))\", route=~\"api_(v1|prom)_push|otlp_v1_metrics\",status_code=~\"5.+\"}[$__rate_interval])) /\nsum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-distributor.*))\", route=~\"api_(v1|prom)_push|otlp_v1_metrics\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Writes 99th latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (k8s_cluster_unique_name_job_route:cortex_request_duration_seconds_bucket:sum_rate{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-distributor.*))\", route=~\"api_(v1|prom)_push|otlp_v1_metrics\"}))\n"
    }
   ]
  },
  {
   "title": "Reads - 2xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-query-frontend.*))\", route=~\"(prometheus|api_prom)_api_v1_.+\",status_code=~\"2.+\"}[$__rate_interval])) /\nsum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-query-frontend.*))\", route=~\"(prometheus|api_prom)_api_v1_.+\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Reads - 4xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-query-frontend.*))\", route=~\"(prometheus|api_prom)_api_v1_.+\",status_code=~\"4.+\"}[$__rate_interval])) /\nsum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-query-frontend.*))\", route=~\"(prometheus|api_prom)_api_v1_.+\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Reads - 5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-query-frontend.*))\", route=~\"(prometheus|api_prom)_api_v1_.+\",status_code=~\"5.+\"}[$__rate_interval])) /\nsum(rate(cortex_request_duration_seconds_count{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-query-frontend.*))\", route=~\"(prometheus|api_prom)_api_v1_.+\"}[$__rate_interval]))\n"
    }
   ]
  },
  {
   "title": "Reads 99th latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (k8s_cluster_unique_name_job_route:cortex_request_duration_seconds_bucket:sum_rate{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-query-frontend.*))\", route=~\"(prometheus|api_prom)_api_v1_.+\"}))\n"
    }
   ]
  },
  {
   "title": "Unhealthy pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n> 0\n",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "kube_statefulset_status_replicas_current{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"} -\nkube_statefulset_status_replicas_ready {k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"}\n> 0\n",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "Pods count per version",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "count by(container, version) (\n  label_replace(\n    kube_pod_container_info{k8s_cluster_unique_name=~\"$cluster\", service_namespace=~\"$namespace\"},\n    \"version\", \"$1\", \"image\", \".*:(.*)\"\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Latency vs 24h ago",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n  avg_over_time(histogram_quantile(0.99, sum by (le) (k8s_cluster_unique_name_job_route:cortex_request_duration_seconds_bucket:sum_rate{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-distributor.*))\", route=~\"api_(v1|prom)_push|otlp_v1_metrics\"} offset 24h))[1h:])\n  /\n  avg_over_time(histogram_quantile(0.99, sum by (le) (k8s_cluster_unique_name_job_route:cortex_request_duration_seconds_bucket:sum_rate{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-distributor.*))\", route=~\"api_(v1|prom)_push|otlp_v1_metrics\"}))[1h:])\n)\n",
     "legendFormat": "writes"
    },
    {
     "expr": "1 - (\n  avg_over_time(histogram_quantile(0.99, sum by (le) (k8s_cluster_unique_name_job_route:cortex_request_duration_seconds_bucket:sum_rate{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-query-frontend.*))\", route=~\"(prometheus|api_prom)_api_v1_.+\"} offset 24h))[1h:])\n  /\n  avg_over_time(histogram_quantile(0.99, sum by (le) (k8s_cluster_unique_name_job_route:cortex_request_duration_seconds_bucket:sum_rate{k8s_cluster_unique_name=~\"$cluster\", job=~\"($namespace)/((mimir-query-frontend.*))\", route=~\"(prometheus|api_prom)_api_v1_.+\"}))[1h:])\n)\n",
     "legendFormat": "reads"
    }
   ]
  }
 ]
}